### ISSUE TITLE
Decrease block delay value in Delegated consensus

### ISSUE THREAD

**Issue by dnkolegov** [filecoin-project/eudico#143]
### Improvement Suggestion

Delegated consensus [mines](https://github.com/filecoin-project/eudico/blob/eudico/chain/consensus/delegcns/mine.go#L38) 1 block in 30 seconds.
Can we decrease this block delay?

**Comment by adlrocha** [comment]
Yes, this is a configurable parameter. Eudico is compiled with `tags=2k', which means that we inherit the build params from `params_2k.go`: https://github.com/filecoin-project/eudico/blob/5a49fbc1dba5eb2407f6de165e3cf89453c5dfab/build/params_2k.go#L99

By default we have a 1sec `BlockDelay`, we can leave it like this, or add a cli flag to `delegated` to make it configurable without requiring changes to any build param.

**Comment by dnkolegov** [comment]
Yes, it works. The most important concern was how to use delegated consensus with `itests`. 
I will add tags itests runner.
