### ISSUE TITLE
Tendermint CI environment

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/eudico#182]
We are currently skipping Tendermint itests in CI because we don't have a proper environment to run it. We are deferring this until we decide if it is worth the effort (i.e. if we end up moving Tendermint to production as part of HC)
https://github.com/filecoin-project/eudico/blob/deb9c365b39cad742200c86f6385194be8f2618d/itests/eudico_subnet_test.go#L39

**Comment by dnkolegov** [comment]
Closed due to https://github.com/filecoin-project/eudico/issues/224
