### ISSUE TITLE
Remove dead code from Tendermint consensus

### ISSUE THREAD

**Issue by adlrocha** [filecoin-project/eudico#224]
We've decided not to maintain the Tendermint consensus as part of Eudico anymore. To avoid having dead code in our base code we should remove all Tendermint-specific code. My suggestion would be to:
- Create a new branch to freeze the code with Tendermint in case we want to come back to it or re-use it in the future.
- Remove it from the main branch and make a pointer to the Tendermint branch in the consensus README in case someone wants to make the effort of coming the code back to life again.

**Comment by dnkolegov** [comment]
Created a frozen branch - https://github.com/filecoin-project/eudico/tree/archive/tendermint-ref-final

**Comment by dnkolegov** [comment]
Fixed in https://github.com/filecoin-project/eudico/pull/242
